---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: social-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: social-service
        image: chinhluu2907/social-service:latest
        ports:
        - containerPort: 4007
        env:
        - name: NODE_ENV
          value: production
  selector:
    matchLabels:
      app: social-service
---
apiVersion: v1
kind: Service
metadata:
  name: social-service
spec:
  type: LoadBalancer
  ports:
  - port: 4007
    targetPort: 4007
  selector:
    app: social-service
